@startuml 🌐 API SNCF - Flux principaux 
title 🌐 API SNCF - Flux principaux

skinparam backgroundColor #f9fafc
skinparam participant {
  BackgroundColor #ffffff
  BorderColor #333
  FontColor #333
}

actor Agent #ffcc00
participant "Frontend React" as Front #b3d9ff
participant "API SNCF" as API #b2f7ef
database "MongoDB" as DB #ffd6a5

== 🟦 Requête GET : Récupération des gare ==

Agent -[#blue]-> Front : va sur la map
Front -[#blue]-> API : <b>GET</b> /v1/data/gares/
API -[#blue]-> DB : requête MongoDB
DB -[#green,dashed]-> API : Données gares (JSON)
API -[#green]-> Front : <b>200 OK</b> (JSON ok)
Front -[#black]-> Agent : affiche les gares sur la carte

== 🟦 Requête GET : Récupération d'une gare ==

Agent -[#blue]-> Front : recherche une gare (ex : <b>Paris</b>)
Front -[#blue]-> API : <b>GET</b> /v1/data/gares/{id}/
API -[#blue]-> DB : requête MongoDB
DB -[#green,dashed]-> API : données de la gare Paris
API -[#green]-> Front : <b>200 OK</b> (JSON gare)
Front -[#black]-> Agent : affiche la gare sur la carte

== 🟧 Requête POST : Ajout d'une gare ==

Agent -[#orange]-> Front : entre une nouvelle ville
Front -[#orange]-> API : <b>POST</b> /v1/data/gares/{id}/
API -[#orange]-> DB : insertion MongoDB
DB -[#green,dashed]-> API : <b>200 OK</b>
API -[#green]-> Front : JSON de confirmation
Front -[#black]-> Agent : gare ajoutée à la carte

== 🟥 Requête DELETE : Ajout d'une gare ==
Agent -[#orange]-> Front : entre le nom d'une ville
Front -[#orange]-> API : <b>POST</b> /v1/data/gares/{id}/
API -[#orange]-> DB : Suppression de MongoDB
DB -[#green,dashed]-> API : <b>200 OK</b>
API -[#green]-> Front : JSON de confirmation
Front -[#black]-> Agent : gare supprimée à la carte

@enduml
