@startuml 🌐 API SNCF - Flux principaux 
title 🌐 API SNCF - Flux principaux

skinparam backgroundColor #f9fafc
skinparam participant {
  BackgroundColor #ffffff
  BorderColor #333
  FontColor #333
}

actor Agent #ffcc00
participant "Frontend React" as Front #b3d9ff
participant "API SNCF" as API #b2f7ef
database "MongoDB" as DB #ffd6a5

== 🟦 Requête GET : Récupération de la catégorie ==

Agent -[#blue]-> Front : va sur la map
Front -[#blue]-> API : <b>GET</b> /v1/data/categories/
API -[#blue]-> DB : requête MongoDB
DB -[#green,dashed]-> API : Données catégorie (JSON)
API -[#green]-> Front : <b>200 OK</b> (JSON ok)
Front -[#black]-> Agent : affiche les données sur la carte

== 🟦 Requête GET : Récupération d'une catégorie ==

Agent -[#blue]-> Front : recherche une catégorie (ex : <b>Paris</b>)
Front -[#blue]-> API : <b>GET</b> /v1/data/categories/{id}/
API -[#blue]-> DB : requête MongoDB
DB -[#green,dashed]-> API : données de la catégorie Paris
API -[#green]-> Front : <b>200 OK</b> (JSON catégorie)
Front -[#black]-> Agent : affiche la catégorie sur la carte

== 🟧 Requête POST : Ajout d'une catégorie ==

Agent -[#orange]-> Front : ajoute un élément d'une catégorie
Front -[#orange]-> API : <b>POST</b> /v1/data/categories/{id}/
API -[#orange]-> DB : insertion de la donnée dans MongoDB
DB -[#green,dashed]-> API : <b>200 OK</b>
API -[#green]-> Front : JSON de confirmation
Front -[#black]-> Agent : catégorie ajoutée à la carte

== 🟥 Requête DELETE : Ajout d'une catégorie ==
Agent -[#orange]-> Front : supprime un élément d'une catégorie
Front -[#orange]-> API : <b>POST</b> /v1/data/categories/{id}/
API -[#orange]-> DB : Suppression de la donnée dans MongoDB
DB -[#green,dashed]-> API : <b>200 OK</b>
API -[#green]-> Front : JSON de confirmation
Front -[#black]-> Agent : donnée supprimée de la carte

@enduml
